### PR TITLE
Add datetime on hover

### PR DESCRIPTION
**Pull request by vietanhdev**
Add date time beside stars when hovering a time point. Resolve this issue: #9 

image

### CODE REVIEW

**Review by dtolnay — CHANGES_REQUESTED** [review]
Thanks! 2 comments:

- I don't think second-level precision is warranted ("1/12/2022, 5:07:23 PM"). How about doing date only? That's what the issue asked for.

- The text gets cut off near the left edge of the graph. Could you think of any approaches to mitigate this?

**Comment by dtolnay** [comment]
Also: I think people are going to be confused why multiple different dates might be shown. I would prefer if only 1 date were shown regardless of number of lines on the graph, and it should be exactly the date that the black line is pointing to, regardless of when the stars occurred.

<br>

**Comment by dtolnay** [comment]
Something along these lines, maybe:

**Comment by vietanhdev** [comment]
@dtolnay Resolved the issues. Please check my results. Thank you.

**Review by dtolnay — CHANGES_REQUESTED** [review]
It's still showing wrong dates. Look at this screenshot where it's showing a date in September even though the cursor is at least halfway into October. Also the positioning of the text looks unpleasant, and the circle that's supposed to be on the intersection between the curve and the vertical black line is in the wrong place.

<br>

**Pull request closed without merging**
